repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
      additional_dependencies: [
        "flake8-annotations",
        "flake8-docstrings",
        "flake8-import-order",
        "flake8-tidy-imports",
      ]
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black