[package]
name = "day_01"
version = "0.1.0"
authors = ["S. Co1 <sco1.git@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
normalize-line-endings = "0.3"
